### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Habraken**
Updated README.md to correct incorrect path to *.elf files and added a hit that a second terminal is required to get the debugger to load the desired elf file.

### CODE REVIEW

**Comment by jwhui** [comment]
> Updated README.md to correct incorrect path to *.elf files and added a hit that a second terminal is required to get the debugger to load the desired elf file.

@Habraken , thanks for submitting this PR. Are you able to sign the Google CLA? https://github.com/openthread/ot-samr21/pull/177/checks?check_run_id=4512365276

**Comment by Habraken** [comment]
@Jonathan, yes I am working on it. It should be sorted in ~ 24hrs.

**Comment by Habraken** [comment]
@jonathan, 
I have managed to sort out the CLA, finally. However it may be linked to my alternate email address. Can you please check it again?

**Comment by jwhui** [comment]
> @jwhui, I have managed to sort out the CLA, finally. However it may be linked to my alternate email address. Can you please check it again?

@Habraken , I can confirm that you have signed the CLA. However, the email address associated with your CLA does not match the one used in your commit. Can you update your commit so that it uses your gmail adddress?

**Comment by Habraken** [comment]
@jwhui 
I have been able to add my other email address to the CLA.

**Comment by jwhui** [comment]
> @jwhui I have been able to add my other email address to the CLA.

@Habraken , the CLA check is passing now. Thanks!

The pretty check failure remains. You can run `./script/make-pretty markdown` to automatically fix the formatting.

**Comment by Habraken** [comment]
@jwhui, I have ran the make-pretty script. Everything should pass now.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

**Pull request merged**
